export const Proflist = [
    {
        id: 0,
        droneId: 12890,
        status: "Active",
        lservice: "31st Jan 2020",
        issues: "None",
        next: "6th Apr 2020",
        droneId: 12890,
        speed: "89 kmph",
        battery: "89%",
        distance: "4 km",
        weight: "0.5 kg",
    },
    {
        id: 1,
        droneId: 12890,
        status: "Active",
        lservice: "31st Jan 2020",
        issues: "None",
        next: "6th Apr 2020",
        droneId: 12890,
        speed: "89 kmph",
        battery: "89%",
        distance: "4 km",
        weight: "0.5 kg",
    },
    {
        id: 2,
        droneId: 12890,
        status: "Inactive",
        lservice: "31st Jan 2020",
        issues: "None",
        next: "6th Apr 2020",
        droneId: 12890,
        speed: "89 kmph",
        battery: "89%",
        distance: "4 km",
        weight: "0.5 kg",
    },
    {
        id: 3,
        droneId: 12890,
        status: "Active",
        lservice: "31st Jan 2020",
        issues: "None",
        next: "6th Apr 2020",
        droneId: 12890,
        speed: "89 kmph",
        battery: "89%",
        distance: "4 km",
        weight: "0.5 kg",
    },
]